 <h1 style="color:orange; font-weight:bold"># 🔍 Data Inconsistency — Finding & Fixing Hidden Data Problems</h1>

<div align="center">

<img src="data_inconsistancy.png" alt="Missing Values Handling — From Basic to Advanced" width="100%">

</div>

## 📌 What is Data Inconsistency?

Data inconsistency occurs when the same type of information is stored in different, incorrect, duplicated, or logically conflicting ways.

In this notebook, we will identify and handle five common types of data inconsistency:

### 1. 📅 Inconsistent Formats
The same information is stored in different formats.

**Example:**
- `DD-MM-YYYY`
- `YYYY-MM-DD`
- `DD/MM/YYYY`
- `19th of December 2022`

👉 Convert them into one consistent format, such as `DD-MM-YYYY`.

### 2. 🌍 Inconsistent Naming Conventions
The same entity is represented using different names.

**Example:**
- `U.S.A`
- `USA`
- `United States`
- `United States of America`

👉 Standardize them to one value, such as `USA`.

### 3. ✏️ Typographical Errors
Spelling or capitalization mistakes create different values.

**Example:**
- `Pakistan`
- `Pakstan`
- `Paakistan`
- `pakistan`

👉 Standardize them to `Pakistan`.

### 4. 🔁 Duplication
The same value appears more than once when it should be unique.

**Example:**
- `Shahzaib`
- `Ahmad`
- `John`
- `Shahzaib`
- `Mateen`

👉 Detect and handle the duplicate `Shahzaib`.

### 5. ⚠️ Contradictory Data
Values conflict with basic logical rules.

**Example:**

**Logical:**
`Son's Age < Father's Age`  
`40 < 50` ✅

**Contradictory:**
`Son's Age > Father's Age`  
`50 > 40` ❌

> 🎯 **Goal:** Detect inconsistencies → Understand the problem → Standardize or correct the data → Prepare it for reliable analysis.

### 👤 Author
**Shahzaib Abdul Khaliq**

🔗 **LinkedIn:** https://www.linkedin.com/in/shahzaibabdulkhaliq/  
💻 **GitHub:** https://github.com/Shahzaibabdulkhaliq0  
📊 **Kaggle:** https://www.kaggle.com/shezibaba

---
---

<h3 style="color:orange; font-weight:bold">📅 Inconsistent Formats</h3>

* **Same information → different formats.**
* ⚠️ Different formats can cause problems in **sorting, filtering, and analysis**.
* ✅ Convert them into **one consistent format**.

### Example

`DD-MM-YYYY`
`YYYY-MM-DD`
`DD/MM/YYYY`
`19th of December 2022`

👉 Standardize them into one format, e.g. **`DD-MM-YYYY`**.

> 💡 **Rule:** Same data → **One consistent format.**

In [37]:
# Import Liberary
import pandas as pd

In [38]:
# Manually Create New Dataset
data = {
    'date': ['2021-12-01', '01-12-2022', '2022/12/01', '12-01-2021'],
    'country': ['USA', 'U.S.A.', 'America', 'United States'],
    'name': ['Aammar', 'Amaar', 'Hamza', 'Hazma'],
    'sales_2020': [100, 200, None, 200],
    'sales_2021': [None, 150, 300, 150]
}

In [39]:
# mConvert into Pandas DataFrame
df = pd.DataFrame(data)

In [40]:
df.head()

         date        country    name  sales_2020  sales_2021
0  2021-12-01            USA  Aammar       100.0         NaN
1  01-12-2022         U.S.A.   Amaar       200.0       150.0
2  2022/12/01        America   Hamza         NaN       300.0
3  12-01-2021  United States   Hazma       200.0       150.0

In [41]:
# Standarizing the Date Formats
df['date'] = pd.to_datetime(df['date'], errors='coerce')
df['date'].dt.strftime('%Y-%m-%d')

0    2021-12-01
1           NaN
2           NaN
3           NaN
Name: date, dtype: str

In [42]:
# Customize By Your Choice
df['date'] = pd.to_datetime(df['date'], errors='coerce')
df['date'].dt.strftime('%d-%m-%Y')  ## Simply Changing Here in Format

0    01-12-2021
1           NaN
2           NaN
3           NaN
Name: date, dtype: str

In [43]:
df['date'] = pd.to_datetime(df['date'], errors='coerce')
df['date'].dt.strftime('%d.%m.%Y')

0    01.12.2021
1           NaN
2           NaN
3           NaN
Name: date, dtype: str

In [44]:
df['date'] = pd.to_datetime(df['date'], errors='coerce')
df['date'].dt.strftime('%d/%m/%Y')

0    01/12/2021
1           NaN
2           NaN
3           NaN
Name: date, dtype: str

<h3 style="color:orange; font-weight:bold">🌍 Inconsistent Naming Conventions</h3>

* **Same entity → different names or representations.**
* ⚠️ This can create **duplicate categories** during grouping, counting, and analysis.
* ✅ Standardize all variations into **one consistent name**.

### Example

`U.S.A`
`USA`
`United States`
`United States of America`

👉 Convert all into one value: **`USA`**

> 💡 **Rule:** Same entity → **One consistent name.**

In [45]:
# Harmonize the name of the coutry
country_mapping = {'U.S.A.': 'USA', 'America': 'USA','United States': 'USA'}
df['country'] = df['country'].replace(country_mapping)

In [46]:
df.head()

        date country    name  sales_2020  sales_2021
0 2021-12-01     USA  Aammar       100.0         NaN
1        NaT     USA   Amaar       200.0       150.0
2        NaT     USA   Hamza         NaN       300.0
3        NaT     USA   Hazma       200.0       150.0

<h3 style="color:orange; font-weight:bold">✏️ Typographical Errors</h3>

* **Typing or spelling mistakes → inconsistent values.**
* ⚠️ Even a small mistake can create a **separate category** in the dataset.
* ✅ Correct spelling and standardize capitalization.

### Example

`Pakistan`
`Pakstan`
`Paakistan`
`pakistan`

👉 Standardize them to: **`Pakistan`**

> 💡 **Rule:** Spelling + capitalization → **Keep them consistent.**

In [47]:
# Correct the typographical Mistakes in name
# Let's assume we want to correct 'Amaar' to 'Aammar'
df['name'] = df['name'].replace({'Amaar': 'Aammar', 'Hazma': 'Hamza'})

In [48]:
df.head()

        date country    name  sales_2020  sales_2021
0 2021-12-01     USA  Aammar       100.0         NaN
1        NaT     USA  Aammar       200.0       150.0
2        NaT     USA   Hamza         NaN       300.0
3        NaT     USA   Hamza       200.0       150.0

<h3 style="color:orange; font-weight:bold">🔁 Duplication</h3>

* **Same value appears more than once in a column.**
* ⚠️ Duplicates can lead to **incorrect counting and analysis**.
* ✅ Identify and handle duplicate values appropriately.

### Example

```text
Aammar
Aammar
Hamza
Hamza
```

👉 **`Aammar` appears twice → Duplicate value**

> 💡 **Rule:** Same value repeated → **Check for duplication.**

In [49]:
df.head()

        date country    name  sales_2020  sales_2021
0 2021-12-01     USA  Aammar       100.0         NaN
1        NaT     USA  Aammar       200.0       150.0
2        NaT     USA   Hamza         NaN       300.0
3        NaT     USA   Hamza       200.0       150.0

In [50]:
# Remove Duplicates
df = df.drop_duplicates(subset="name")
df.head()

        date country    name  sales_2020  sales_2021
0 2021-12-01     USA  Aammar       100.0         NaN
2        NaT     USA   Hamza         NaN       300.0

In [51]:
df.head()

        date country    name  sales_2020  sales_2021
0 2021-12-01     USA  Aammar       100.0         NaN
2        NaT     USA   Hamza         NaN       300.0

<h3 style="color:orange; font-weight:bold">⚠️ Contradictory Data</h3>

* **Data that violates a logical relationship or real-world rule.**
* ⚠️ Contradictory values can make the dataset **logically incorrect**.
* ✅ Check whether related values follow the expected relationship.

### Example

**Logical:**

`Age of Son < Age of Father`

`40 < 50` ✅

**Contradictory:**

`Age of Son > Age of Father`

`50 > 40` ❌

> 💡 **Rule:** Related values must follow their **logical relationship**.

In [52]:
# Resolving Contradictory Data
# For demonstration, let's assume sales_2021 should always be higher than sales_2020
# We'll remove rows where this condition is not met
df = df.drop(df[df['sales_2021'] <= df['sales_2020']].index)

In [53]:
df.head()

        date country    name  sales_2020  sales_2021
0 2021-12-01     USA  Aammar       100.0         NaN
2        NaT     USA   Hamza         NaN       300.0

## 🎯 Data Inconsistency — Final Takeaway

Data inconsistency means the **same or related information is stored incorrectly, differently, or in conflicting forms**.

### 🔍 What We Learned

- 📅 **Inconsistent Formats** → Standardize formats
- 🌍 **Inconsistent Naming** → Use one consistent name
- ✏️ **Typographical Errors** → Correct spelling and capitalization
- 🔁 **Duplication** → Identify repeated values
- ⚠️ **Contradictory Data** → Check logical relationships

> 💡 **Final Rule:** Before analysis or Machine Learning, always **Detect → Analyze → Standardize → Fix** data inconsistencies.