<h1 style="color:orange; font-weight:bold">🔗 Data Integration</h1>
<h3 style="color:green; font-weight:bold">Combining Data from Multiple Sources</h3>

<div align="center">

<img src="05_data_integration.png" alt="Missing Values Handling — From Basic to Advanced" width="100%">

</div>

<h4 style="color:Red; font-weight:bold">🔗 Data Integration</h4>

Data Integration means **combining data from different datasets into one useful dataset**.

### 📌 Methods Covered

- 🔗 **Data Merging**
- 🧩 **Data Concatenation**

> 💡 **Goal:** Combine related datasets without losing important information.

---
---

<h3 style="color:orange; font-weight:bold">🔗 Data Merging</h3>

- **Merging = Combining two datasets using a common column.**
- Usually, a common **key/ID** is used to connect the data.
- `pd.merge()` is used in Pandas.

### Example

**Dataset 1**

| ID | Name |
|---|---|
| 1 | Ahmed |
| 2 | Fatima |

**Dataset 2**

| ID | City |
|---|---|
| 1 | Karachi |
| 2 | Lahore |

👉 Merge using `ID` → Name + City in one dataset.

> 💡 **Rule:** Common key → **Merge related information.**
---

In [2]:
import pandas as pd

# Example datasets for data merging
# Dataset 1: Pakistani Individuals
data1 = {
    'id': [1, 2, 3],
    'name': ['Ahmed', 'Fatima', 'Ali'],
    'age': [28, 32, 24]
}
df1 = pd.DataFrame(data1)
df1.head()

   id    name  age
0   1   Ahmed   28
1   2  Fatima   32
2   3     Ali   24

In [3]:
# Dataset 2: Additional Information
data2 = {
    'id': [1, 2, 3],
    'city': ['Karachi', 'Lahore', 'Islamabad'],
    'occupation': ['Engineer', 'Doctor', 'Teacher']
}
df2 = pd.DataFrame(data2)
df2.head()

   id       city occupation
0   1    Karachi   Engineer
1   2     Lahore     Doctor
2   3  Islamabad    Teacher

In [4]:
# Merging DataFrames on 'id'
merged_df = pd.merge(df1, df2, on='id', how='inner')
merged_df.head()

   id    name  age       city occupation
0   1   Ahmed   28    Karachi   Engineer
1   2  Fatima   32     Lahore     Doctor
2   3     Ali   24  Islamabad    Teacher

<h3 style="color:orange; font-weight:bold">🧩 Concatenation</h3>

- **Concatenation = Joining DataFrames together.**
- `axis=0` → Add **rows**
- `axis=1` → Add **columns**
- `pd.concat()` is used in Pandas.

### Example

**Rows**

`Ahmed, Fatima`  
➕  
`Ali, Sara`

👉 One DataFrame with **more rows**.

**Columns**

`Name + Age`  
➕  
`City + Province`

👉 One DataFrame with **more columns**.

> 💡 **Rule:** `axis=0` → **Rows** | `axis=1` → **Columns**
---

In [5]:
import pandas as pd

# Example datasets for Pakistani context
# Dataset 1 - Pakistani Names and Ages
data1 = {'Name': ['Ahmed', 'Fatima', 'Ali'], 'Age': [28, 32, 24]}
# Dataset 2 - More Pakistani Names and Ages
data2 = {'Name': ['Sara', 'Usman', 'Aisha'], 'Age': [29, 35, 27]}
# Dataset 3 - Cities and Provinces in Pakistan
data3 = {'City': ['Karachi', 'Lahore', 'Islamabad'], 'Province': ['Sindh', 'Punjab', 'Islamabad']}

df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)
df3 = pd.DataFrame(data3)

# Concatenating Rows
concatenated_rows = pd.concat([df1, df2])

# Concatenating Columns
# Note: For a meaningful column-wise concatenation, dataframes should have the same number of rows.
concatenated_columns = pd.concat([df1, df3], axis=1)
print(concatenated_rows)
print(";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;")
concatenated_columns

     Name  Age
0   Ahmed   28
1  Fatima   32
2     Ali   24
0    Sara   29
1   Usman   35
2   Aisha   27
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

     Name  Age       City   Province
0   Ahmed   28    Karachi      Sindh
1  Fatima   32     Lahore     Punjab
2     Ali   24  Islamabad  Islamabad

## 🎯 Data Integration — Final Takeaway

- 🔗 **Merge** → Combine related data using a **common key**.
- 🧩 **Concat** → Join DataFrames by **rows or columns**.

> 💡 **Remember:**  
> **Merge = Connect related data**  
> **Concat = Stack data together**