<h1 style="color:orange; font-weight:bold">🔤 Feature Encoding</h1>

<div align="center">

<img src="feature_encoding.png" alt="Missing Values Handling — From Basic to Advanced" width="100%">

</div>

**Feature Encoding = Converting categorical/text data into numerical values so Machine Learning models can process it.**

### ❓ Why Do We Need Encoding?

- 🤖 ML models mainly work with **numerical data**.
- 🔤 Categorical values like `Male`, `Female`, `Pakistan`, `India` are **text**, not numbers.
- 🔢 Encoding converts these categories into **numbers**.
- 📊 This makes categorical features usable for **training and prediction**.

### Example

Before:

`Gender = Male, Female, Male`

After Encoding:

`Gender = 1, 0, 1`

> 💡 **Rule:** **Categorical Data → Numerical Data → ML Model**
---

<h3 style="color:orange; font-weight:bold">🏷️ Label Encoding</h3>

- **Label Encoding = Converts each category into a numerical label.**
- Each unique category gets a **different integer**.
- ✅ Useful for **ordinal categories** where order matters.

### Example

`Low → 0`  
`Medium → 1`  
`High → 2`

👉 The numbers represent the **order of the categories**.

> 💡 **Rule:** Label Encoding → **Categories → Integer Labels**
---

In [2]:
# Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, OrdinalEncoder

In [3]:
# Load Dataset
df = sns.load_dataset('tips')
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [4]:
df['time'].value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [5]:
# Let Select LabelEncoder() From SKlearn
le = LabelEncoder()

In [6]:
df['encoded_time'] = le.fit_transform(df['time'])

In [7]:
df['encoded_time'].value_counts()

encoded_time
0    176
1     68
Name: count, dtype: int64

In [8]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size',
       'encoded_time'],
      dtype='str')

In [9]:
df['day'].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [10]:
df['encoded_day'] = le.fit_transform(df['day'])

In [11]:
df['encoded_day'].value_counts()

encoded_day
1    87
2    76
3    62
0    19
Name: count, dtype: int64

In [12]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,encoded_time,encoded_day
0,16.99,1.01,Female,No,Sun,Dinner,2,0,2
1,10.34,1.66,Male,No,Sun,Dinner,3,0,2
2,21.01,3.50,Male,No,Sun,Dinner,3,0,2
3,23.68,3.31,Male,No,Sun,Dinner,2,0,2
4,24.59,3.61,Female,No,Sun,Dinner,4,0,2

---
<h3 style="color:orange; font-weight:bold">🏷️ OrdinalEncoder</h3>

- **OrdinalEncoder = Converts categorical values into numerical values based on their order.**
- ✅ Best for **ordinal categories** where a meaningful ranking exists.
- You can **define the order** of the categories.

### Example

`Low → 0`  
`Medium → 1`  
`High → 2`

👉 The numbers represent the **real order** of the categories.

> 💡 **Rule:** OrdinalEncoder → **Ordered Categories → Ordered Numbers**

In [13]:
# Ordinal Encoding 'day' Column Using Specific Order
encode = OrdinalEncoder(categories=[['Thur', 'Fri', 'Sat', 'Sun']])

In [14]:
# Run Model for Convert into Ordinal Encoding
df['encoded_day'] = encode.fit_transform(df[['day']])

In [15]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,encoded_time,encoded_day
0,16.99,1.01,Female,No,Sun,Dinner,2,0,3.0
1,10.34,1.66,Male,No,Sun,Dinner,3,0,3.0
2,21.01,3.50,Male,No,Sun,Dinner,3,0,3.0
3,23.68,3.31,Male,No,Sun,Dinner,2,0,3.0
4,24.59,3.61,Female,No,Sun,Dinner,4,0,3.0

---
<h3 style="color:orange; font-weight:bold">🔢 One-Hot Encoding</h3>

- **One-Hot Encoding = Converts each category into a separate binary column.**
- Each category gets **`1` if present and `0` otherwise**.
- ✅ Best for **nominal categories** where there is **no meaningful order**.

### Example

`Color = Red, Blue, Green`

After One-Hot Encoding:

| Color | Red | Blue | Green |
|---|---:|---:|---:|
| Red | 1 | 0 | 0 |
| Blue | 0 | 1 | 0 |
| Green | 0 | 0 | 1 |

> 💡 **Rule:** One-Hot Encoding → **One Category = One Binary Column.**

In [16]:
# One-Hot Encoding on 'day' Column
encoder = OneHotEncoder()

In [17]:
# Run Model for Convert into One-Hot Encoding
encode = encoder.fit_transform(df[['sex']]).toarray()

In [18]:
# Convert into Pandas DataFrame
data = pd.DataFrame(encode)

In [19]:
data.head()

     0    1
0  1.0  0.0
1  0.0  1.0
2  0.0  1.0
3  0.0  1.0
4  1.0  0.0

<h4 style="color:green; font-weight:bold">🔢 2 Method</h4>

In [35]:
# Load Dataset
data = sns.load_dataset('titanic')

In [25]:
# Load Encoder
onehot_encoder = OneHotEncoder(sparse_output=False)

In [26]:
# Fit & Transform
embarked_onehot = onehot_encoder.fit_transform(titanic[['embarked']])

In [27]:
# Convert into Pandas DataFrame
embarked_onehot_df = pd.DataFrame(embarked_onehot, columns=onehot_encoder.get_feature_names_out(['embarked']))

In [28]:
# Concantinate
titanic = pd.concat([titanic.reset_index(drop=True), embarked_onehot_df.reset_index(drop=True)], axis=1)

In [29]:
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,embarked_C,embarked_Q,embarked_S,embarked_nan
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,0.0,0.0,1.0,0.0
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,1.0,0.0,0.0,0.0
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,0.0,0.0,1.0,0.0
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,0.0,0.0,1.0,0.0
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,0.0,0.0,1.0,0.0

<h4 style="color:green; font-weight:bold">🔢 3 Method</h4>

In [36]:
# Load Dataset
titanic = sns.load_dataset('titanic')

In [37]:
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [38]:
import category_encoders as ce

encoder = ce.OneHotEncoder(cols=['embarked'])

titanic = encoder.fit_transform(titanic)

titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked_1,embarked_2,embarked_3,embarked_4,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,1,0,0,0,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,0,1,0,0,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,1,0,0,0,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,1,0,0,0,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,1,0,0,0,Third,man,True,NaN,Southampton,no,True

---
<h3 style="color:orange; font-weight:bold">🔢 Binary Encoding</h3>

- **Binary Encoding = Converts categories into binary (0/1) values using binary digits.**
- It uses **fewer columns** than One-Hot Encoding when there are many categories.
- ✅ Useful for **high-cardinality categorical features**.

### Example

Categories:

`Red, Blue, Green, Yellow`

Binary codes:

`Red → 00`  
`Blue → 01`  
`Green → 10`  
`Yellow → 11`

> 💡 **Rule:** Binary Encoding → **Categories → Binary digits → Fewer columns.**

In [ ]:
# Import Liberary
from category_encoders import BinaryEncoder

In [39]:
# Load Dataset
df = sns.load_dataset('tips')
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [40]:
# Use Pandas Get Dummies
get_dummies = pd.get_dummies(df, columns=['day'])

In [41]:
get_dummies.head()

,total_bill,tip,sex,smoker,time,size,day_Thur,day_Fri,day_Sat,day_Sun
0,16.99,1.01,Female,No,Dinner,2,False,False,False,True
1,10.34,1.66,Male,No,Dinner,3,False,False,False,True
2,21.01,3.50,Male,No,Dinner,3,False,False,False,True
3,23.68,3.31,Male,No,Dinner,2,False,False,False,True
4,24.59,3.61,Female,No,Dinner,4,False,False,False,True

---
## 🎯 Feature Encoding — Final Summary

Feature Encoding converts **categorical data into numerical form** so that Machine Learning models can process it.

### 🔑 Methods Covered

- 🏷️ **Label Encoding** → Categories → Integer labels
- 📊 **Ordinal Encoding** → Ordered categories → Ordered numbers
- 🔢 **One-Hot Encoding** → Categories → Binary columns
- 💻 **Binary Encoding** → Categories → Binary digits

> 💡 **Final Rule:** Choose the encoding method based on whether your categories have a **meaningful order** and how many categories your feature contains.