<h1 style="color:orange; font-weight:bold">🌲 Random Forest</h1>

<div align="center">

<img src="15_random_forest.png" alt="Missing Values Handling — From Basic to Advanced" width="100%">

</div>

**Random Forest** is a powerful **Ensemble Learning** algorithm that combines multiple Decision Trees to make better predictions.

### 🎯 Main Uses

* 🏷️ **Classification**
* 📈 **Regression**
* 🔄 Works well with **large datasets** and complex relationships.

### ⚙️ How Random Forest Works?

`Dataset → 🎲 Random Samples → 🌳 Multiple Decision Trees → 🗳️ Aggregate Results → 🎯 Prediction`

* 🎲 **Bagging** → Creates different samples from the dataset **with replacement** and builds a tree for each sample.
* 🎯 **Random Feature Selection** → Each tree considers a random subset of features.
* 🗳️ **Aggregation** → **Majority Vote** for Classification and **Average** for Regression.

### ⭐ Key Features

* 🛡️ **Robustness** → Less prone to overfitting by combining multiple trees.
* 🔀 **Handles Non-Linearity** → Captures complex relationships.
* 🔍 **Feature Importance** → Shows which features contribute more to predictions.

### ✅ Advantages

* 🎯 Often provides **high predictive accuracy**
* 🔄 Supports **Classification & Regression**
* 🧩 Works well with complex datasets
* 👶 Relatively easy to use

### 🌍 Applications

* 🏦 **Banking** → Credit Scoring
* 🏥 **Healthcare** → Disease Identification
* 🛒 **E-Commerce** → Product Recommendation
* 📈 **Finance** → Market Prediction

### ⚠️ Considerations

* 🌳 More trees → Better performance, but **higher computational cost**
* 📏 Deeper trees → More information, but may increase **overfitting**
* 🎯 **Relevant features** are important for good performance

### 🚧 Challenges

* 🧩 **Interpretability** → Harder to interpret than a single Decision Tree
* 💻 **Computationally Intensive** → Large forests require more resources

> 💡 **Rule:**
> **Random Forest = Multiple Randomized Decision Trees + Aggregation → Stronger Prediction.**
---

---
<h3 style="color:orange; font-weight:bold">🏷️ Random Forest Classification</h3>

Random Forest Classification predicts a categorical class by combining the predictions of multiple Decision Trees.

⚙️ How It Works

Dataset → 🎲 Random Samples → 🌳 Multiple Trees → 🗳️ Majority Vote → 🏷️ Final Class

🌳 Each tree makes its own classification.
🗳️ The class receiving the most votes becomes the final prediction.
🔀 Random samples and features help make the forest more robust.
🧠 Example

Tree 1 → Spam
Tree 2 → Not Spam
Tree 3 → Spam
Tree 4 → Spam

Majority Vote → Spam 📧

💡 Rule: Random Forest Classification → Multiple Trees + Majority Voting → Final Class.

In [22]:
# Import Libraries
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

In [23]:
# Load the Data
df = sns.load_dataset('tips')
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [24]:
# Encode Features
le = LabelEncoder()
for i in df.columns:
    if df[i].dtype == 'object' or df[i].dtype == 'category':
        df[i] = le.fit_transform(df[i])
df.head()

   total_bill   tip  sex  smoker  day  time  size
0       16.99  1.01    0       0    2     0     2
1       10.34  1.66    1       0    2     0     3
2       21.01  3.50    1       0    2     0     3
3       23.68  3.31    1       0    2     0     2
4       24.59  3.61    0       0    2     0     4

In [25]:
# Split the data into X and y for classification
X = df.drop('sex', axis = 1)
y = df['sex']

# Train Test Split the Data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=42)

# Call the Model
model_cl = RandomForestClassifier(n_estimators=200, random_state=42)

# Train the Model
model_cl.fit(X_train, y_train)

# Predict Model
y_pred = model_cl.predict(X_test)

# Evaluate the Model
print('accuracy score: ', accuracy_score(y_test, y_pred))
print('confusion matrix:\n', confusion_matrix(y_test, y_pred))
print('classification report:\n', classification_report(y_test, y_pred))

accuracy score:  0.6122448979591837
confusion matrix:
 [[ 7 12]
 [ 7 23]]
classification report:
               precision    recall  f1-score   support

           0       0.50      0.37      0.42        19
           1       0.66      0.77      0.71        30

    accuracy                           0.61        49
   macro avg       0.58      0.57      0.57        49
weighted avg       0.60      0.61      0.60        49

---
<h3 style="color:orange; font-weight:bold">📈 Random Forest Regression</h3>

Random Forest Regression predicts a continuous numerical value by combining the predictions of multiple Decision Trees.

⚙️ How It Works

Dataset → 🎲 Random Samples → 🌳 Multiple Trees → 📊 Average Predictions → 🎯 Final Value

🌳 Each tree makes its own numerical prediction.
📊 The average of all tree predictions becomes the final prediction.
🔀 Random samples and features help make the model more robust.
🧠 Example

Tree 1 → $100K
Tree 2 → $110K
Tree 3 → $105K

Average → $105K 🏠

💡 Rule: Random Forest Regression → Multiple Trees + Average Predictions → Final Numerical Value.

In [26]:
# Import Libraries
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

In [27]:
# Load the Data
df = sns.load_dataset('tips')
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [28]:
# Encode Features
le = LabelEncoder()
for i in df.columns:
    if df[i].dtype == 'object' or df[i].dtype == 'category':
        df[i] = le.fit_transform(df[i])
df.head()

   total_bill   tip  sex  smoker  day  time  size
0       16.99  1.01    0       0    2     0     2
1       10.34  1.66    1       0    2     0     3
2       21.01  3.50    1       0    2     0     3
3       23.68  3.31    1       0    2     0     2
4       24.59  3.61    0       0    2     0     4

In [29]:
# Split the data into X and y for classification
X = df.drop('tip', axis = 1)
y = df['tip']

# Train Test Split the Data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=42)

# Call the Model
model_reg = RandomForestRegressor()

# Train the Model
model_reg.fit(X_train, y_train)

# Predict Model
y_pred = model_reg.predict(X_test)

# Evaluate the Model
print('MSE   : ', mean_squared_error(y_test, y_pred))
print('MAE   : ', mean_absolute_error(y_test, y_pred))
print('R2    : ', r2_score(y_test, y_pred))
print('RMSE  : ', np.sqrt(mean_squared_error(y_test, y_pred)))

MSE   :  0.9804895800000015
MAE   :  0.780110204081633
R2    :  0.2155903543644737
RMSE  :  0.9901967380273485

---
## 🎯 Random Forest — Final Takeaway

### 🔑 What We Practiced

* 🌳 Understood how **multiple Decision Trees** work together as an ensemble.
* 🎲 Connected **Bagging** with random sampling and multiple trees.
* 🔀 Understood why **random feature selection** is used.
* 🗳️ Learned how individual tree outputs are combined into one final prediction.
* 🔍 Understood the importance of **feature selection, tree depth, and number of trees**.
* ⚖️ Recognized the trade-off between **performance and computational cost**.

### 📚 Level

🟡 **Intermediate ML Model** → Random Forest is more advanced than a single Decision Tree because it introduces **Ensemble Learning, Bagging, and Random Feature Selection**.

> 💡 **Final Rule:**
> **Random Forest = Multiple Decision Trees working together → More robust predictions.**